.gitignore, package.json
Added NPM's package-lock.json file to `.gitignore` since we are primarily using Yarn for this project.  This is to make it so if someone uses NPM instead they will not commit the file to the project by mistake.
=> Add the NPM package-lock.json file to git ignore

src/docs/border.md, src/docs/display.md, src/docs/links.md, src/docs/spacing.md, src/docs/text-utils.md, src/docs/typography.md, src/docs/visibility.md, src/docs/z-index.md, styleguide.config.js
Added documentation with more samples from the Rivet pages to fill in some examples of how to use Rivet utilities and other styling with the React components.
This also changes the style guide so it creates a page per section since it was starting to get fairly lengthy.
=> Added non-component samples

src/components/Badge/Badge.md, src/components/Badge/Badge.test.tsx, src/components/Badge/Badge.tsx, src/components/Button/Button.md, src/components/Button/Button.test.tsx, src/components/Button/Button.tsx, src/components/Button/ButtonGroup.md
Renames the role property on Badge and Button to be named modifier instead to avoid collision with the ARIA role attribute.
Fixes #79
=> Rename the role property to modifier

package.json, yarn.lock
All packages are updated except for:
* `react*` (breaks build)
* `enzyme*` (breaks tests)
* `typescript` (too soon)
Upgrades validated with `yarn build && yarn test --coverage && yarn start`.
Current output of `yarn outdated`:
```
Package                        Current Wanted Latest  Package Type    URL
@types/enzyme                  3.1.10  3.1.10 3.1.13  devDependencies https://github.com/DefinitelyTyped/DefinitelyTyped.git
@types/enzyme-adapter-react-16 1.0.2   1.0.2  1.0.3   devDependencies https://github.com/DefinitelyTyped/DefinitelyTyped.git
@types/react                   16.4.1  16.4.1 16.4.11 devDependencies https://github.com/DefinitelyTyped/DefinitelyTyped.git
@types/react-dom               16.0.6  16.0.6 16.0.7  devDependencies …
```
=> Freeze all package versions and update to latest where possible.

src/components/Badge/Badge.tsx, src/components/Button/Button.tsx, src/components/Input/common.tsx, src/components/List/List.tsx, src/components/Panel/Panel.tsx, src/components/Table/Table.tsx
This drops the "default" option which was not intended for users to use and changes the checks to use undefined instead.
=> Remove the default option from several enum types

.circleci/config.yml
Now that we've merged 0.3.0 (yay!), `master` should be the exclusive source for `gh-pages`.
=> Don't publish gh-pages from develop

package.json
These two dependencies should not be required by consumers of the library since they are used to build and test it so this change moves them to the devDependencies section of package.json.
=> Move jest-cli and react-scripts-ts to devDependencies

package.json, yarn.lock
`rivet-uits` caused checksum conflicts when pulled from the IU NPM registry. It is only necessary to produce the style guide and can be moved to `devDependencies`.
Resolves #114
=> fix(npm): Move `rivet-uits` to `devDependencies`

.circleci/config.yml
The NPM package is being published without any components. I think it's because semantic-release expects them to be built already. This PR adds a task to take care of that.
=> fix(ci): Build components prior to publishing NPM package

src/components/Checkbox/Checkbox.test.tsx, src/components/Checkbox/Checkbox.tsx
The "rvt-sr-only" class was being applied to the label when the label visibility was changed and that kept the entire checkbox from appearing.  This was fixed by applying the sr-only class to an inner span instead.
=> Fix display issue with sr-only label on a Checkbox

addons/index.js, package.json, src/components/Addons/Switch/Switch.md, src/components/Addons/Switch/Switch.test.tsx, src/components/Addons/Switch/Switch.tsx, src/components/Addons/Switch/index.ts, src/components/Addons/index.ts, styleguide.config.js, yarn.lock
Adds support for addon components which are kept in a separate submodule.  The instructions for this component include details on how to leverage the component since it requires an additional NPM module and a different sort of import.
=> Add support for addons and the switch component

src/components/Header/HeaderIdentity.tsx
This corrects two display issues in the header identity menu when it is rendered in a drawer:
* If you did not have a logout action handler there would be an extra right border which was not necessary
* If you have an identity menu with no children it did not have a consistent bottom border like the other elements.  This is a CSS bug in Rivet but is being fixed here for the time being.
=> Fixes two display issues with the header identity menu in the drawer

package.json, src/components/Alert/Alert.md, src/components/Alert/Alert.test.tsx, src/components/Alert/DismissibleAlert.md, src/components/Alert/DismissibleAlert.test.tsx, src/components/Alert/InlineAlert.test.tsx, src/components/Alert/common.ts, src/components/Badge/Badge.md, src/components/Badge/Badge.test.tsx, src/components/Badge/Badge.tsx, src/components/Input/Input.test.tsx, src/components/Input/Select.test.tsx, src/components/Input/Textarea.test.tsx, src/components/Input/common.tsx, src/components/Panel/Panel.md, src/components/Panel/Panel.test.tsx, src/components/RadioButton/RadioButton.test.tsx, src/components/Table/Table.md, src/components/Table/Table.test.tsx, src/components/Table/Table.tsx, src/components/Tabs/Tabs.md, src/components/util/Rivet.test.tsx, src/components/util/Rivet.tsx, src/components/util/validation.tsx, yarn.lock
- Adds compact and cell table variants
- Adds lr and tb edges
- Adds new typescale aliases
- Consistent color naming: info, success, warning, danger
=> Update Rivet version 1.1.0

package.json
A couple of weeks ago when I released 0.5.0 I'm guessing I did something wrong which prevented semantic-release from updating this appropriately so I'm fixing this now.  This should cause 0.6.0 to be created when we merge the recent changes into master.
=> chore(package): Fix the package version number after last release

src/components/Pagination/Pagination.test.tsx, src/components/Pagination/Pagination.tsx
Modified the Pagination component so it checks for the disabled attribute in addition to the aria-disabled attribute when determining if a pagination item should be disabled
=> Add disabled class to pagination item if child is disabled

src/components/Alert/InlineAlert.md, src/components/Alert/InlineAlert.test.tsx, src/components/Alert/InlineAlert.tsx, src/components/Input/Input.md, src/components/Input/Input.test.tsx, src/components/Input/Select.md, src/components/Input/Select.test.tsx, src/components/Input/Textarea.md, src/components/Input/Textarea.test.tsx, src/components/Input/common.tsx, src/components/util/validation.tsx
The variant options for `InlineAlert` as well as for the various input components that use `InlineAlert`, were still using the `valid` and `invalid` variants, that are no longer used in Rivet and also inconsistent with other components. 
This also removes the `validationClass()` method from `validation.tsx` as the translation is no longer necessary.
=> Fix/clean up variant options in InlineAlert and input components

src/components/File/File.tsx
You would get a compiler error when trying to import `rivet-react@0.6.1` into a typescript project
```Failed to compile.
/app/node_modules/rivet-react/build/dist/components/File/File.d.ts
(18,110): Cannot find module '../src/components/util/Rivet'.```
=> fix(File): tsx files were not finding correct path to this module

src/components/File/File.md, src/components/File/File.test.tsx, src/components/File/File.tsx, src/components/util/Rivet.test.tsx
This removes the state formerly used and leans more heavily on the native HTML File API, allowing clearing the selected file and description by resetting the containing form.
It also adds an optional `innerRef` prop, which allows a parent component to access the file input element.
=> Add ability to clear the selected file and description

src/components/util/RivetIcons.tsx
The rivet icons were previously read as simply "image" by screen readers. This changes the behavior to instruct screen readers to ignore them. Note that this change is only applied to icons without title tags.
=> fix(accessibility): Adds aria-hidden to Icons

src/components/Header/Header.test.tsx, src/components/Header/Header.tsx
The skip to content link will not currently work if a base tag is present (it will always return the user to `/#main-content`). Adding the full URL allows it to preserve the user's page in the application.
closes #193
=> feat(Accessibility): Use Full URL in "Skip to Content" Link Location

src/components/Header/Header.test.tsx, src/components/Header/Header.tsx
Changes the behavior of the skip to content link so it doesn't append multiple anchors to the URL on subsequent selection events.
Closes #193
=> fix(Accessibility): Fix "Skip To Content" Link

src/components/Header/Header.tsx
The argument name `string` in an anonymous filter callback conflicts with the string type declaration, preventing the styleguide from building.
=> fix(Documentation): Fix anonymous function argument

package.json, src/components/Footer/Footer.test.tsx, src/components/Footer/Footer.tsx
* Update rivet and associated add-ons
* Update footer to match new Rivet styling
BREAKING CHANGE: Updates to a new minor version of Rivet
=> feat(upgrade): Upgrade Rivet and Add-Ons

src/components/Alert/Alert.test.tsx, src/components/Alert/Alert.tsx
The `Alert` component has an optional title prop. If this is provided, a title header tag is created with a generated id and `aria-labelledby` references this id in the parent. However, this prop was being added to the parent even when there was no title, creating a reference to an id that was not in the dom.
=> feat: ESIMW-2399: Fix Alert accessibility issue

src/components/Input/Input.jsx, src/components/Input/Input.md, src/components/Input/Input.test.jsx, src/components/Input/Select.jsx, src/components/Input/Select.md, src/components/Input/Select.test.jsx, src/components/Input/Textarea.jsx, src/components/Input/Textarea.md, src/components/Input/Textarea.test.jsx, src/components/Input/common.jsx, src/components/Input/index.jsx, src/components/index.js, src/components/util/Rivet.jsx, styleguide.config.cjs
1. The spacing and width of these components looks different then 1.0 because of changes to various classNames (example: rvt-container-sm rvt-p-all-xxl-lg-up rvt-m-bottom-md rvt-p-all-lg).
a. Examples before:
b. Examples after:
3. In order to fix this warning (also for Select & Textarea):
`Warning: src/components/Input/Input.jsx matches a pattern defined in “components” or “sections” options in your style guide config but doesn’t export a component.`
I changed renderInput in common.jsx from a higher order function to a regular one and added an empty component (`<>{renderInput("input", props)}</>`). That gets rid of the warning at the expense of slightly wordy code
I am interested in feedback if anybody spots flaws / improvements on the above. Thanks!
=> Build Input (Input, Textarea, Select) Components

.circleci/config.yml, jest.config.cjs
Code coverage was not being collected and uploaded correctly. This change should prompt the codecov bot to comment on this PR indicating code coverage is working again.
=> ci: reenable code coverage

src/components/Footer/BaseFooter.jsx
Fix a typo in the documentation for the BaseFooter privacyLink property.
=> docs: fix privacylink typo in BaseFooter component

src/components/Alert/Alert.jsx, src/components/Alert/Alert.test.jsx, src/components/Alert/DismissibleAlert.jsx, src/components/Alert/DismissibleAlert.test.jsx, src/components/util/TestUtils.js
Currently when using the DismissableAlert component a generated Id is always used during render even if developers supply an id property to the component.  This is because id is one of the properties declared and deconstructed from the passed in props but it is not then passed through to the Alert component used for render so the Alert generates an id.  This PR removes several declared properties in the DismissableAlert component that are not directly used there so that they are passed through with the rest of the "other" properties to the Alert component.
=> fix: Rendered provided id for dismissed alerts (#439)

.circleci/config.yml
New versions of semantic-release require newer Node LTS features. Also update the Circle CI orbs (`node` and `codecov`).
=> ci: update ci node version

src/components/Header/BaseHeader.jsx, src/components/Header/BaseHeader.test.jsx, src/components/Header/Header.jsx, src/components/Header/Header.test.jsx
Fluid headers will likely be desirable for dynamic applications so set them as the default, but support containerized widths for more static content.
Closes #464
=> feat: support fluid header width

src/components/Header/BaseHeader.jsx, src/components/Header/BaseHeader.test.jsx, src/components/Header/Header.jsx, src/components/Header/Header.test.jsx
Make the content href a required property on `Header` and `BaseHeader` so it is enforced that users set it consciously.
=> feat: #467 make content href customizable

src/components/Header/BaseHeader.jsx, src/components/Header/BaseHeader.md, src/components/Header/BaseHeader.test.jsx, src/components/Header/BaseHeaderMenuItem.jsx, src/components/Header/BaseHeaderMenuItem.md, src/components/Header/BaseHeaderMenuItem.test.jsx, src/components/PageContent/Card/Card.jsx, src/components/PageContent/Card/Card.md
Adding onClick handlers to a couple components so that we can override the default behavior in their nested anchor tags and use, for example, `react-router`'s `navigate()` function.
=> feat: Add onClick behavior to BaseHeader and BaseHeaderMenuItem components - closes #471

src/components/Header/BaseHeader.test.jsx, src/components/Header/Header.test.jsx, src/components/PageContent/Badge/Badge.jsx, src/components/PageContent/Badge/Badge.test.jsx, src/components/Sidenav/Sidenav.test.jsx
The `Badge` property `type` is a reserved keyword and does not match the rest of the components which have modifiers.
=> fix: fix test warnings and update badge modifier property name

src/components/Dialog/Dialog.jsx, src/components/Dialog/Dialog.md
The `dialog` role is not currently being applied to dialogs when `disablePageInteraction` is set.
=> fix: #401 add dialog role to all dialogs

package-lock.json, package.json, src/components/Header/BaseHeader.md, src/components/Header/BaseHeaderMenu.md, src/components/Header/BaseHeaderMenuItem.md, src/components/Header/BaseHeaderNavigation.md, src/components/Header/Header.jsx, src/components/Header/Header.md, src/components/Header/HeaderAvatar.md, src/components/Header/HeaderNavigation.jsx, src/components/Header/childUtils.jsx, src/components/PageContent/EmptyState/EmptyState.md, src/components/Pagination/Pagination.md, styleguide.setup.js
* Use memoized child dependency in HeaderNavigation to determine when children change and key them with a UUID.
* Fix missing contentHref and icons in markdown documentation files.
=> fix: #475 fix header navigation child key warnings

package-lock.json, package.json, src/components/Dialog/Dialog.jsx, src/components/Dialog/Dialog.test.jsx
I adjusted #480, I believe the role needs to be an attribute instead of as part of style.
For the focus work I settled on adding a new library. Adobe react-aria supports focus trapping (and it works) but I couldn't get it to work in our code base. It probably has to do with the ref object we pass into the library. I tried to replicate the adobe react-aria code but it turned out messy and I called it quits before I got it working. Finally I settled on using focus-trap-react which looks rather clean. Of course it's "one more library"...
Long term I hope we can migrate to HTML5 dialog but as we discussed in the last few days it is not accessibility ready.
Let me know what you think, thanks!
=> fix: #401 Adjust role fix and add focus handling

.husky/pre-commit, package-lock.json, package.json, src/components/Dialog/Dialog.md
In development environments, the modals which allow closing on outside interactions were being immediately closed because the button event which opened them was also triggering a close.
=> fix: #491 fix dialog examples

package.json
We were receiving a warning in CI that the repository field was misconfigured.
=> chore: fix package.json repository field

src/components/Accordion/Accordion.test.jsx, src/components/Accordion/AccordionPanel.jsx
The commit type was `feature:` instead of `feat:` so a release was not triggered. This PR will be followed by another PR to re-apply the changes with the proper commit type.
=> chore: EPMDW-3684 - Revert changes to accordion so they can be re-applied properly

src/components/Accordion/Accordion.test.jsx, src/components/Accordion/AccordionPanel.jsx
This re-implements [the change](https://github.com/indiana-university/rivet-react/pull/538) to the `AccordionPanel` `title` prop and will use the correct commit type to trigger a release.
=> feat: EPMDW-3684 - Allow node for AccordionPanel title prop - Closes #537
