indiana-university/rivet-react

src/Demo.tsx, src/components/Button/ButtonGroup.test.tsx, src/components/Button/ButtonGroup.tsx, src/components/Button/index.ts
Adds the button group component described in https://rivet.uits.iu.edu/components/forms/buttons/#button-groups
=> Implement ButtonGroup component

src/components/Badge/Badge.test.tsx, src/components/Badge/Badge.tsx, src/components/Badge/index.tsx, src/components/index.tsx
Adds a Badge component and tests as described in https://rivet.uits.iu.edu/components/page-content/badges/
=>  Implement Badge component

src/components/Input/Select.md, src/components/Input/Select.test.tsx, src/components/Input/Select.tsx, src/components/Input/index.ts, styleguide.config.js
Implement the `Select` component
=> /issues/72/select

src/components/Header/Header.md, src/components/Header/Header.test.tsx, src/components/Header/Header.tsx, src/components/Header/HeaderIdentity.md, src/components/Header/HeaderIdentity.test.tsx, src/components/Header/HeaderMenu.md, src/components/Header/HeaderNavigation.md, src/components/Header/HeaderNavigation.test.tsx, src/components/Header/index.ts, src/components/Modal/Modal.md, src/components/Modal/Modal.test.jsx, src/components/Modal/Modal.tsx, src/components/Modal/ModalBody.md, src/components/Modal/ModalControls.md, src/components/Modal/index.ts, styleguide.config.js
=> Remove dot notation from Header and Modal

src/components/Alert/Alert.md, src/components/Alert/DismissibleAlert.md, src/components/Alert/InlineAlert.md, src/components/Alert/InlineAlert.tsx, src/components/Alert/common.ts, src/components/Input/common.tsx, src/components/util/validation.tsx
This PR improve documentation for `Alert`, `DismissibleAlert`, and `InlineAlert`. I also took the opportunity to refactor and refine some validation class/icon code that is shared by both Alerts and Inputs.
=> Improve Alert documentation; refactor

src/components/util/RivetIcons.test.tsx, src/components/util/RivetIcons.tsx
Just some housekeeping I meant to do on the last svg branch.
=> Refactor Icon component

package.json, src/components/Footer/Footer.md, src/components/Footer/Footer.test.tsx, src/components/Footer/Footer.tsx, src/components/index.tsx, src/components/util/Rivet.test.tsx, src/components/util/Rivet.tsx, yarn.lock
Removed dependencies on `Rivet.Nav` and `react-router-dom`.
=> Refactor Footer and improve docs 

src/components/Alert/InlineAlert.tsx, src/components/Input/Input.md, src/components/Input/Input.tsx, src/components/Input/Select.md, src/components/Input/Select.tsx, src/components/Input/Textarea.md, src/components/Input/Textarea.tsx, src/components/Input/common.tsx, src/components/util/validation.tsx, styleguide.config.js
I did a pretty big refactor to tidy up src/Input/common.tsx, remove some of the type verbosity, and (I hope) make things a little more React-y.
=> Improve Input docs; refactor 

.circleci/config.yml, CONTRIBUTING.md, README.md, package.json, yarn.lock
[Semantic Release](https://github.com/semantic-release/semantic-release) is a workflow for using structured commit messages to determine the next version number of a package in accordance with [semantic versioning](https://semver.org/) principles. The semantic-release process introduced in this PR will perform the following steps on a push to `master`:  
1. Select the next version number based on commit logs since the last release;  
2. Tag the GH commit with that version number;  
3. Create a release from the tag with auto-generated release notes;  
4. Add a friendly comment to any PRs referenced by the release notes, that the given PR was included in the release;  
5. Push the package to NPM with the new version.  
The current version of semantic-release only supports releasing from a …
=> chore(ci): Add semantic-release to CI workflow

src/components/Alert/DismissibleAlert.tsx, src/components/Badge/Badge.tsx, src/components/Dropdown/Dropdown.tsx, src/components/Grid/Col.tsx, src/components/Grid/Container.tsx, src/components/Grid/Row.tsx, src/components/Panel/Panel.tsx, src/components/Section/Section.tsx, src/components/Table/Table.tsx
=> fix(ts): Change `Rivet` import to prevent compilation error in TS projects

src/components/Breadcrumbs/Breadcrumbs.md, src/components/Breadcrumbs/Breadcrumbs.test.tsx, src/components/Breadcrumbs/Breadcrumbs.tsx, src/components/Breadcrumbs/index.ts, src/components/index.tsx, styleguide.config.js
https://rivet.uits.iu.edu/components/navigation/breadcrumb/
=> Add breadcrumb support

package.json, src/components/Addons/Collapse/Collapse.md, src/components/Addons/Collapse/Collapse.test.tsx, src/components/Addons/Collapse/Collapse.tsx, src/components/Addons/Collapse/index.ts, src/components/Addons/index.ts, src/components/util/RivetIcons.tsx, styleguide.config.js, yarn.lock
See https://rivet.uits.iu.edu/add-ons/rivet-collapsible/
=> Add collapse add-on support

src/components/Pagination/Pagination.md, src/components/Pagination/Pagination.test.tsx, src/components/Pagination/Pagination.tsx, src/components/Pagination/index.ts, src/components/index.tsx, styleguide.config.js
See https://rivet.uits.iu.edu/components/navigation/pagination/
=> feat(Pagination): Add pagination support

src/components/Button/Button.test.tsx, src/components/Button/Button.tsx, src/components/Pagination/Pagination.tsx
This also cleans up some indentation issues in the Pagination component
=> Remove logic to make button disabled if no onClick provider is specified

package.json, src/components/Alert/InlineAlert.md, src/components/Alert/InlineAlert.test.tsx, src/components/Alert/InlineAlert.tsx, src/components/File/File.tsx, src/components/Input/Input.md, src/components/Input/Input.test.tsx, src/components/Input/Select.md, src/components/Input/Select.test.tsx, src/components/Input/Textarea.md, src/components/Input/Textarea.test.tsx, src/components/Input/common.tsx, src/components/Tabs/Tabs.test.tsx, src/components/Tabs/Tabs.tsx, src/components/util/validation.tsx
- consistent color naming (danger vs invalid)
- Tab component accessibility fixes
- File component tsx bug fix
=> 0.6.2 release

src/components/Addons/Collapse/Collapse.tsx, src/components/Alert/Alert.tsx, src/components/Dropdown/Dropdown.tsx, src/components/Header/HeaderCollapse.tsx, src/components/Header/HeaderDrawer.tsx, src/components/Modal/Modal.tsx, src/components/Tabs/Tabs.tsx
=> Add button type to prevent unintended form submission

src/components/Modal/Modal.test.jsx
=> fix(Modal): Modal close button submits parent

src/components/Dropdown/Dropdown.md, src/components/Dropdown/Dropdown.tsx, src/components/Dropdown/DropdownEvent.ts
Reverts indiana-university/rivet-react#206
=> Revert "Feature/toggle dropdown click inside"

src/components/util/RivetIcons.jsx, src/components/util/RivetIcons.test.jsx, src/components/util/TestUtils.js
Initial RivetIcon(s) that Dropdown needs. Hopefully allows for the addition of future Icons
=> RivetIcons initial (caret-down only)

src/components/Alert/DismissibleAlert.jsx, src/components/Alert/InlineAlert.jsx, src/components/Alert/InlineAlert.md, src/components/Alert/InlineAlert.test.jsx, src/components/Alert/index.jsx
Add the inline alert component along with documentation and tests.
=> feat: add inline alert #297

src/components/Dropdown/DropdownEventUtilsTest.test.js, src/components/Dropdown/index.jsx, src/components/util/EventUtils.js, src/components/util/EventUtils.test.js
These tests were in [AbstractUserActionEvent.test.ts](https://github.com/indiana-university/rivet-react/blob/master/src/components/util/AbstractUserActionEvent.test.ts) in v1. I forgot to add them while working on the Dropdown component.
=> Added tests for EventUtils.js

.circleci/config.yml, .gitignore, package-lock.json, package.json
Use JUnit reporter to store tests results and configure CircleCI to store them
=> ci: store test results

src/components/Button/Button.jsx, src/components/Button/Button.md, src/components/Button/Button.test.jsx, src/components/LoadingIndicator/LoadingIndicator.jsx, src/components/LoadingIndicator/LoadingIndicator.md, src/components/LoadingIndicator/LoadingIndicator.test.jsx, src/components/LoadingIndicator/index.jsx, src/components/index.js, styleguide.config.cjs
* Question: Do we like the component name "LoadingIndicator"?
* I added the Button loading indicator sample to both Button.md and LoadingIndicator.md. The other changes in Button.md is cleanup, prettify seemed to have added some end of line weirdness. Hopefully this sticks
=> 326: Loading Indicator

.circleci/config.yml, lib/main.js, package-lock.json, package.json, src/components/File/index.jsx
* Use codecov CircleCI orb instead of Node dependency
* Export additional modules for more complete build
* Update Rivet-core and Vite
=> feat: update build process

src/components/Header/Header.test.jsx
Provide required title in Header component tests and remove console.log
=> test: fix Header component test warnings

src/components/Accordion/AccordionPanelHeader.jsx, src/components/Checkbox/Checkbox.jsx, src/components/Dropdown/DropdownGroup.jsx, src/components/File/File.jsx, src/components/Footer/ResourceFooter.jsx, src/components/Input/common.jsx, src/components/PageContent/StepIndicator/Step.jsx, src/components/Sidenav/Sidenav.jsx
Looks like there are also some formatting changes which I'm guessing were introduced by prettier
=> feat: EPMDW-3476 - Allow node prop type for labels

package-lock.json, package.json
Update several out of date dev dependencies.
=> ci: update build dependencies

package-lock.json, src/components/Alert/Alert.jsx, src/components/Alert/InlineAlert.jsx, src/components/File/File.jsx, src/components/File/File.test.jsx, src/components/Header/BaseHeader.md, src/components/Header/BaseHeader.test.jsx, src/components/Header/BaseHeaderNavigation.jsx, src/components/Header/BaseHeaderNavigation.test.jsx
The `Header.Avatar` and `Header.Search` components need to be rendered inside the `BaseHeaderNavigation`'s `nav` component, but outside of the navigation `ul`, which was not happening previously.
This change allows the search and avatar components to be added as children to `BaseHeaderNavigation` and the various types of components are placed in their respective locations.
=> fix: 462 - Fix Header.Avatar display - closes #462

jest.config.cjs, package-lock.json, package.json, src/components/Accordion/Accordion.jsx, src/components/Accordion/Accordion.md, src/components/Accordion/Accordion.test.jsx, src/components/Accordion/AccordionPanelHeader.jsx, src/components/Alert/InlineAlert.jsx, src/components/Dialog/Dialog.jsx, src/components/Dropdown/Dropdown.jsx, src/components/File/File.jsx, src/components/File/File.test.jsx, src/components/Footer/BaseFooter.jsx, src/components/Header/BaseHeader.jsx, src/components/Header/BaseHeaderMenu.jsx, src/components/Header/BaseHeaderNavigation.jsx, src/components/Header/BaseHeaderNavigationSecondary.jsx, src/components/Header/HeaderMenu.jsx, src/components/Header/HeaderNavigation.jsx, src/components/Header/HeaderNavigationSecondary.jsx, src/components/Header/HeaderSearch.jsx, src/components/Pagination/PaginationItem.jsx, src/components/Pagination/PaginationItem.test.jsx, src/components/SeriesNav/SeriesNav.jsx, src/components/SeriesNav/SeriesNav.test.jsx, src/components/Sidenav/SidenavMenu.jsx, src/components/util/RivetIcons.jsx, src/components/util/RivetIcons.test.jsx, src/components/util/TestUtils.js
install `rivet-icons@3.0.0` and use it in every place where we were previously using custom SVGs (where possible).
Closes #398
=> feat: #398 use rivet-icons v3

CONTRIBUTING.md
Update the documentation to include all the steps necessary to create a new component in the project.
=> docs: update contribution docs for new components

src/components/Accordion/Accordion.test.jsx, src/components/Layouts/PageNotFound/PageNotFoundLayout.jsx, src/components/Layouts/PageNotFound/PageNotFoundLayout.test.jsx, src/components/PageContent/Badge/Badge.test.jsx, src/components/PageContent/Billboard/Billboard.test.jsx, src/components/PageContent/Calendar/CalendarTile.test.jsx, src/components/PageContent/CallToAction/CallToAction.test.jsx, src/components/PageContent/Card/Card.test.jsx, src/components/PageContent/Disclosure/Disclosure.test.jsx, src/components/PageContent/EmptyState/Actions.jsx, src/components/PageContent/EmptyState/Content.jsx, src/components/PageContent/Hero/Hero.test.jsx, src/components/PageContent/LinkHub/LinkHub.test.jsx, src/components/PageContent/Quote/Quote.test.jsx, src/components/PageContent/Stat/Stat.test.jsx, src/components/PageContent/StepIndicator/StepIndicator.test.jsx, src/components/PageContent/Timeline/Timeline.test.jsx, src/components/Subnav/Subnav.test.jsx, src/components/Tabs/Tabs.test.jsx, src/components/util/RivetStickers.test.jsx, src/components/util/SvgCore.jsx, src/components/util/SvgCore.test.jsx
Previously, the license check wasn't running on pre-commit. This update adds the license to all files where it is missing on the beta branch. Additionally, run prettier on files which had not had it run on them
=> chore: fix licensing and run Prettier
